export const GET_INVOICES = "GET_INVOICES";
export const OPEN_FORM = "OPEN_FORM";
export const CLOSE_FORM = "OCLOSE_FORM";
export const ADD_NEW_INVOICE = "ADD_NEW_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const EDIT_EXISTING_INVOICE = "EDIT_EXISTING_INVOICE";
export const RESET_SELECTED_INVOICE = "RESET_SELECTED_INVOICE";

export const SELECT_INVOICE = "SELECT_INVOICE";
export const SELECT_INVOICE_EDIT = "SELECT_INVOICE_EDIT";
export const CHANGE_INVOICE_STATUS = "CHANGE_INVOICE_STATUS";

export const ADD_ITEM_TO_ITEMS = "ADD_ITEM_TO_ITEMS";
export const DELETE_ITEM = "DELETE_ITEM";

export const FILTERED_INVOICES = "FILTERED_INVOICES";
